### ISSUE TITLE
Add requirements.txt to each folder

### ISSUE THREAD

**Issue by randyzwitch** [tylerjrichards/Getting-Started-with-Streamlit-for-Data-Science#1]
Since you can't guarantee users will read the book in order, nor will they always use/not use your examples, having `requirements.txt` in some folders but not others might be confusing.

Alternatively, move it to the top-level so it only needs to be specified once.

**Comment by randyzwitch** [comment]
For example, from a fresh environment, I was able to use the requirements file for the `clt` directory. Moving to testing the `components_example` directory, I get errors because I don't have those packages installed.

Obviously, I know how to solve this as an experienced Python developer, but it would be better to not have this issue for beginners.

**Comment by tylerjrichards** [comment]
ah this is a good call, I will add requirements.txt to each folder

**Comment by tylerjrichards** [comment]
closing this, added a global requirements.txt file to make this easier
