### ISSUE TITLE
penguins_streamlit throws .secrets error

### ISSUE THREAD

**Issue by randyzwitch** [tylerjrichards/Getting-Started-with-Streamlit-for-Data-Science#3]
![image](https://user-images.githubusercontent.com/2762787/123325322-e3e63600-d505-11eb-98d6-3004e14f7bb7.png)

Possibly solved with a try/catch, but also could have a README or other way to highlight how to make this app work.

**Comment by tylerjrichards** [comment]
added a readme which describes this issue and how it would work, also added readmes for each individual folder.
